"""Monge-Ampère equation solvers.

Two methods:
  1. Iterative relaxation (explicit time-stepping)
  2. Damped Newton iteration with sparse Jacobian

For periodic BCs, we solve for a periodic perturbation ψ where
  φ(x) = ½|x|² + ψ(x)
and the MA equation becomes:
  det(I + D²ψ) = f(x)  ←  f = det(D²φ)

This avoids the non-periodicity of ½|x|².

Both support periodic and Dirichlet boundary conditions.

Reference: Froese & Oberman, "Convergent finite difference solvers for
           viscosity solutions of the elliptic Monge–Ampère equation
           in dimensions two and higher", SINUM 2011.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla

from monge_ampere.boundary import BoundaryCondition
from monge_ampere.operators import (
    directional_second_derivative,
    generate_stencil_directions,
    ma_operator,
)

# ======================================================================
# Result container
# ======================================================================


@dataclass
class SolverResult:
  """Output from a Monge-Ampère solver."""
  u: np.ndarray  # the perturbation ψ (periodic) or full u
  residual_history: list[float] = field(default_factory=list)
  converged: bool = False
  iterations: int = 0


# ======================================================================
# Modified MA operator for perturbation formulation
# ======================================================================


def _ma_perturbation(
    psi: np.ndarray,
    h: float,
    stencil_pairs: list[tuple[tuple[int, int], tuple[int, int]]],
    bc: BoundaryCondition,
    bv: np.ndarray | None = None,
) -> np.ndarray:
  """Compute det(I + D²ψ) using the monotone wide-stencil scheme.

    For each direction pair (v, w):
      D²_v φ = D²_v(½|x|² + ψ) = (v·v)/|v|² + D²_v ψ = 1 + D²_v ψ

    Wait - that's not right. For v = (v₁, v₂):
      D²_v (½|x|²) = [½|(x+hv)|² + ½|(x-hv)|² - |x|²] / (h|v|)²
                    = [h²|v|²] / (h²|v|²) = 1

    So D²_v φ = 1 + D²_v ψ for any direction v, regardless of |v|.

    det_{monotone}(D²φ) = min_{(v,w)} (1 + D²_v ψ)(1 + D²_w ψ)
    """
  result = np.full_like(psi, np.inf)

  for v, w in stencil_pairs:
    d2v = directional_second_derivative(psi, h, v, bc, bv)
    d2w = directional_second_derivative(psi, h, w, bc, bv)
    candidate = (1.0 + d2v) * (1.0 + d2w)
    np.minimum(result, candidate, out=result)

  return result


# ======================================================================
# Iterative (explicit relaxation) solver
# ======================================================================


def solve_ma_iteration(
    rhs: np.ndarray,
    h: float,
    *,
    dw: int = 2,
    tol: float = 1e-8,
    max_iter: int = 50_000,
    dt: float | None = None,
    bc: BoundaryCondition = BoundaryCondition.PERIODIC,
    bc_func: Callable | None = None,
    u0: np.ndarray | None = None,
    stencil_pairs: list | None = None,
) -> SolverResult:
  """Solve det(D²u) = rhs via explicit time-stepping.

    For PERIODIC BCs, solves in perturbation form:
      det(I + D²ψ) = rhs
    with ψ periodic, so the full potential is φ = ½|x|² + ψ.

    For DIRICHLET BCs, solves the full equation:
      det(D²u) = rhs  with u = bc_func on boundary.

    Args:
      rhs: Right-hand side f(x).
      h: Grid spacing.
      dw: Stencil width.
      tol: Convergence threshold (L∞ residual).
      max_iter: Max iterations.
      dt: Time-step; auto-chosen if None.
      bc: Boundary condition.
      bc_func: Dirichlet boundary values.
      u0: Initial guess for ψ (periodic) or u (Dirichlet).
      stencil_pairs: Autogenerated if None.

    Returns:
      SolverResult.
    """
  N, M = rhs.shape
  if stencil_pairs is None:
    stencil_pairs = generate_stencil_directions(dw)

  bv = None
  if bc is BoundaryCondition.DIRICHLET and bc_func is not None:
    x = np.linspace(0, 1, N)
    y = np.linspace(0, 1, M)
    X, Y = np.meshgrid(x, y, indexing="ij")
    bv = bc_func(X, Y)

  # Initial guess
  if u0 is not None:
    u = u0.copy()
  else:
    u = np.zeros((N, M))  # ψ = 0 → φ = ½|x|² → det = 1
    if bc is BoundaryCondition.DIRICHLET and bv is not None:
      # For Dirichlet, initial guess is ½|x|²
      x = np.linspace(0, 1, N)
      X, Y = np.meshgrid(x, x, indexing="ij")
      u = 0.5 * (X**2 + Y**2)
      u[0, :] = bv[0, :]
      u[-1, :] = bv[-1, :]
      u[:, 0] = bv[:, 0]
      u[:, -1] = bv[:, -1]

  if dt is None:
    dt = 0.25 * h * h

  use_perturbation = (bc is BoundaryCondition.PERIODIC)
  result = SolverResult(u=u)

  for it in range(max_iter):
    if use_perturbation:
      ma_val = _ma_perturbation(u, h, stencil_pairs, bc, bv)
    else:
      ma_val = ma_operator(u, h, stencil_pairs, bc, bv, dw)

    residual = ma_val - rhs
    res_norm = np.max(np.abs(residual))
    result.residual_history.append(float(res_norm))

    if res_norm < tol:
      result.converged = True
      result.iterations = it + 1
      result.u = u
      return result

    # For the perturbation approach, the linearization of
    # det(I + D²ψ) near ψ = 0 is  Δψ + 1, so the "Laplacian"
    # drives convergence. Use a simple update:
    update = dt * residual

    if bc is BoundaryCondition.DIRICHLET:
      update[0, :] = 0.0
      update[-1, :] = 0.0
      update[:, 0] = 0.0
      update[:, -1] = 0.0

    u = u + update

    # Pin the mean of ψ to zero (periodic gauge freedom)
    if use_perturbation:
      u -= np.mean(u)

  result.converged = False
  result.iterations = max_iter
  result.u = u
  return result


# ======================================================================
# Newton solver
# ======================================================================


def _compute_perturbation_ma_and_active(
    psi: np.ndarray,
    h: float,
    stencil_pairs: list[tuple[tuple[int, int], tuple[int, int]]],
    bc: BoundaryCondition,
    bv: np.ndarray | None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
  """Compute det(I+D²ψ) and track the active direction pair.

    Returns:
      ma_val, d2v_active, d2w_active, pair_idx
    """
  N, M = psi.shape
  ma_val = np.full((N, M), np.inf)
  pair_idx = np.zeros((N, M), dtype=int)
  d2v_all = []
  d2w_all = []

  for k, (v, w) in enumerate(stencil_pairs):
    d2v = directional_second_derivative(psi, h, v, bc, bv)
    d2w = directional_second_derivative(psi, h, w, bc, bv)
    candidate = (1.0 + d2v) * (1.0 + d2w)
    mask = candidate < ma_val
    ma_val = np.where(mask, candidate, ma_val)
    pair_idx = np.where(mask, k, pair_idx)
    d2v_all.append(d2v)
    d2w_all.append(d2w)

  d2v_active = np.empty_like(psi)
  d2w_active = np.empty_like(psi)
  for k in range(len(stencil_pairs)):
    mask = pair_idx == k
    d2v_active[mask] = d2v_all[k][mask]
    d2w_active[mask] = d2w_all[k][mask]

  return ma_val, d2v_active, d2w_active, pair_idx


def _assemble_jacobian_perturbation(
    psi: np.ndarray,
    h: float,
    stencil_pairs: list[tuple[tuple[int, int], tuple[int, int]]],
    bc: BoundaryCondition,
    bv: np.ndarray | None,
    d2v_active: np.ndarray,
    d2w_active: np.ndarray,
    pair_idx: np.ndarray,
) -> sp.csr_matrix:
  """Assemble Jacobian of F(ψ) = det(I + D²ψ) - rhs.

    At point (i,j) with active pair (v,w):
      F = (1 + D²_v ψ)(1 + D²_w ψ) - rhs
      ∂F/∂ψ_{kl} = (1+D²_w) · ∂D²_v/∂ψ_{kl} + (1+D²_v) · ∂D²_w/∂ψ_{kl}
    """
  N, M = psi.shape
  n_dof = N * M

  rows = []
  cols = []
  vals = []

  for i in range(N):
    for j in range(M):
      ij = i * M + j
      k = int(pair_idx[i, j])
      v, w = stencil_pairs[k]
      norm_v2 = v[0]**2 + v[1]**2
      norm_w2 = w[0]**2 + w[1]**2
      factor_v = 1.0 + d2v_active[i, j]  # = 1 + D²_v ψ
      factor_w = 1.0 + d2w_active[i, j]  # = 1 + D²_w ψ
      h2v = h * h * norm_v2
      h2w = h * h * norm_w2

      # Contribution from d(D²_v ψ)/dψ multiplied by (1 + D²_w ψ)
      # D²_v ψ stencil: +1/h2v at (i±v), -2/h2v at (i,j)
      center_coeff = 0.0

      for sv in [(v[0], v[1]), (-v[0], -v[1])]:
        if bc is BoundaryCondition.PERIODIC:
          ki = (i + sv[0]) % N
          kj = (j + sv[1]) % M
        else:
          ki = i + sv[0]
          kj = j + sv[1]
          if ki < 0 or ki >= N or kj < 0 or kj >= M:
            continue
        kl = ki * M + kj
        rows.append(ij)
        cols.append(kl)
        vals.append(factor_w / h2v)

      center_coeff += -2.0 * factor_w / h2v

      # Contribution from d(D²_w ψ)/dψ multiplied by (1 + D²_v ψ)
      for sw in [(w[0], w[1]), (-w[0], -w[1])]:
        if bc is BoundaryCondition.PERIODIC:
          ki = (i + sw[0]) % N
          kj = (j + sw[1]) % M
        else:
          ki = i + sw[0]
          kj = j + sw[1]
          if ki < 0 or ki >= N or kj < 0 or kj >= M:
            continue
        kl = ki * M + kj
        rows.append(ij)
        cols.append(kl)
        vals.append(factor_v / h2w)

      center_coeff += -2.0 * factor_v / h2w

      rows.append(ij)
      cols.append(ij)
      vals.append(center_coeff)

  J = sp.coo_matrix((np.array(vals), (np.array(rows), np.array(cols))),
                    shape=(n_dof, n_dof)).tocsr()

  # For Dirichlet: zero out boundary rows and set diagonal to 1
  if bc is BoundaryCondition.DIRICHLET:
    for i in range(N):
      for j in range(M):
        if i == 0 or i == N - 1 or j == 0 or j == M - 1:
          ij = i * M + j
          J[ij, :] = 0
          J[ij, ij] = 1.0

  return J


def solve_ma_newton(
    rhs: np.ndarray,
    h: float,
    *,
    dw: int = 2,
    tol: float = 1e-8,
    max_iter: int = 100,
    bc: BoundaryCondition = BoundaryCondition.PERIODIC,
    bc_func: Callable | None = None,
    u0: np.ndarray | None = None,
    stencil_pairs: list | None = None,
    damping: float = 1.0,
    min_damping: float = 0.01,
) -> SolverResult:
  """Solve det(D²u) = rhs via damped Newton iteration.

    For PERIODIC BCs (perturbation form):
      F(ψ) = det(I + D²ψ) − rhs = 0

    The Jacobian is assembled based on the active direction pair at each point.
    A damped Newton line search is used for globalization.

    For DIRICHLET BCs: solves det(D²u) = rhs with u = bc_func on boundary.

    Args:
      rhs: Right-hand side f(x).
      h: Grid spacing.
      dw: Stencil width.
      tol: Convergence threshold.
      max_iter: Max iterations.
      bc: Boundary condition.
      bc_func: Dirichlet boundary values.
      u0: Initial guess.
      stencil_pairs: Autogenerated if None.
      damping: Initial damping factor.
      min_damping: Minimum damping factor.

    Returns:
      SolverResult.
    """
  N, M = rhs.shape
  if stencil_pairs is None:
    stencil_pairs = generate_stencil_directions(dw)

  bv = None
  if bc is BoundaryCondition.DIRICHLET and bc_func is not None:
    x = np.linspace(0, 1, N)
    y = np.linspace(0, 1, M)
    X, Y = np.meshgrid(x, y, indexing="ij")
    bv = bc_func(X, Y)

  use_perturbation = (bc is BoundaryCondition.PERIODIC)

  # Initial guess
  if u0 is not None:
    u = u0.copy()
  else:
    u = np.zeros((N, M))
    if not use_perturbation and bv is not None:
      x = np.linspace(0, 1, N)
      X, Y = np.meshgrid(x, x, indexing="ij")
      u = 0.5 * (X**2 + Y**2)
      u[0, :] = bv[0, :]
      u[-1, :] = bv[-1, :]
      u[:, 0] = bv[:, 0]
      u[:, -1] = bv[:, -1]

  result = SolverResult(u=u)

  for it in range(max_iter):
    if use_perturbation:
      ma_val, d2v, d2w, pidx = _compute_perturbation_ma_and_active(
          u, h, stencil_pairs, bc, bv)
    else:
      # For Dirichlet, use the standard MA operator
      ma_val = ma_operator(u, h, stencil_pairs, bc, bv, dw)
      # We'll skip Newton for Dirichlet for now (use iteration)
      raise NotImplementedError(
          "Newton solver for Dirichlet BCs not yet implemented. "
          "Use solve_ma_iteration instead.")

    F = ma_val - rhs

    # Pin mean to zero for the periodic case
    if use_perturbation:
      pass
      # The mean of F is related to the compatibility condition
      # rhs should have mean 1 for the perturbation to be well-posed

    res_norm = np.max(np.abs(F))
    result.residual_history.append(float(res_norm))

    if res_norm < tol:
      result.converged = True
      result.iterations = it + 1
      result.u = u
      return result

    # Assemble Jacobian
    J = _assemble_jacobian_perturbation(u, h, stencil_pairs, bc, bv, d2v, d2w,
                                        pidx)

    # For periodic problems, J is singular (constant null space).
    # Pin one DOF or add a regularization.
    if use_perturbation:
      # Add row/column to pin ψ[0,0] = 0
      J[0, :] = 0
      J[0, 0] = 1.0
      F_vec = F.ravel()
      F_vec[0] = u[0, 0]  # drive ψ[0,0] to 0
    else:
      F_vec = F.ravel()

    try:
      delta_u = spla.spsolve(J, -F_vec)
    except Exception:
      delta_u, info = spla.gmres(J, -F_vec, atol=1e-10)
      if info != 0:
        break

    delta_u = delta_u.reshape(N, M)

    # Line search
    alpha = damping
    for _ in range(20):
      u_trial = u + alpha * delta_u
      if use_perturbation:
        u_trial -= np.mean(u_trial)
        ma_trial = _ma_perturbation(u_trial, h, stencil_pairs, bc, bv)
      else:
        ma_trial = ma_operator(u_trial, h, stencil_pairs, bc, bv, dw)

      F_trial = ma_trial - rhs
      res_trial = np.max(np.abs(F_trial))

      if res_trial < res_norm or alpha < min_damping:
        break
      alpha *= 0.5

    u = u_trial

  result.converged = False
  result.iterations = max_iter
  result.u = u
  return result
